name: Docker Compile Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t project-build:latest .

    - name: Run Compile Command in Docker
      run: |
        docker run --rm project-build:latest make

